import Bone02Icon from '@hugeicons/Bone02Icon'
import Brain01Icon from '@hugeicons/Brain01Icon'
import Cardiogram02Icon from '@hugeicons/Cardiogram02Icon'
import DigestionIcon from '@hugeicons/DigestionIcon'
import DoNotTouch01Icon from '@hugeicons/DoNotTouch01Icon'
import FemaleSymbolIcon from '@hugeicons/FemaleSymbolIcon'
import Medicine02Icon from '@hugeicons/Medicine02Icon'
import PatientIcon from '@hugeicons/PatientIcon'

export const specialties = [
  {
    id: 1,
    name: 'General Physician',
    icon: Medicine02Icon,
  },
  {
    id: 2,
    name: 'Cardiologist',
    icon: Cardiogram02Icon,
  },
  {
    id: 3,
    name: 'Orthopedist',
    icon: Bone02Icon,
  },
  {
    id: 4,
    name: 'Gastroenterologist',
    icon: DigestionIcon,
  },
  {
    id: 5,
    name: 'Neurologist',
    icon: Brain01Icon,
  },
  {
    id: 6,
    name: 'Psychiatrist',
    icon: PatientIcon,
  },
  {
    id: 7,
    name: 'Gynecologist',
    icon: FemaleSymbolIcon,
  },
  {
    id: 8,
    name: 'Dermatologist',
    icon: DoNotTouch01Icon,
  },
]

export const doctors = [
  {
    id: 1,
    name: 'Dr. Aatiana Schleifer',
    specialty: 'Neurologist specialist',
    organization: 'Professor of MTB Medicine',
    rating: 5.0,
    reviews: 540,
    specialtyId: 5,
  },
  {
    id: 2,
    name: 'Dr. Ariana Botosh',
    specialty: 'Neurologist specialist',
    organization: 'Professor of MTB Medicine',
    rating: 4.5,
    reviews: 540,
    specialtyId: 5,
  },
  {
    id: 3,
    name: 'Dr. A.Terry Aminoff',
    specialty: 'Neurologist specialist',
    organization: 'Professor of MTB Medicine',
    rating: 5.0,
    reviews: 540,
    specialtyId: 5,
  },
  {
    id: 4,
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiologist specialist',
    organization: 'Professor of Heart Medicine',
    rating: 4.8,
    reviews: 320,
    specialtyId: 2,
  },
  {
    id: 5,
    name: 'Dr. Michael Chen',
    specialty: 'Orthopedist specialist',
    organization: 'Professor of Bone Medicine',
    rating: 4.7,
    reviews: 280,
    specialtyId: 3,
  },
  {
    id: 6,
    name: 'Dr. Emily Davis',
    specialty: 'General Physician',
    organization: 'Professor of General Medicine',
    rating: 4.9,
    reviews: 450,
    specialtyId: 1,
  },
  {
    id: 7,
    name: 'Dr. James Wilson',
    specialty: 'Cardiologist specialist',
    organization: 'Director of Cardiac Institute',
    rating: 4.9,
    reviews: 680,
    specialtyId: 2,
  },
  {
    id: 8,
    name: 'Dr. Maria Rodriguez',
    specialty: 'Gastroenterologist specialist',
    organization: 'Chief of Digestive Medicine',
    rating: 4.6,
    reviews: 420,
    specialtyId: 4,
  },
  {
    id: 9,
    name: 'Dr. Robert Kim',
    specialty: 'Orthopedist specialist',
    organization: 'Senior Consultant Orthopedics',
    rating: 4.8,
    reviews: 390,
    specialtyId: 3,
  },
  {
    id: 10,
    name: 'Dr. Lisa Thompson',
    specialty: 'Psychiatrist specialist',
    organization: 'Head of Mental Health Dept',
    rating: 4.7,
    reviews: 310,
    specialtyId: 6,
  },
  {
    id: 11,
    name: 'Dr. Ahmed Hassan',
    specialty: 'Gynecologist specialist',
    organization: "Professor of Women's Health",
    rating: 4.8,
    reviews: 520,
    specialtyId: 7,
  },
  {
    id: 12,
    name: 'Dr. Jennifer Lee',
    specialty: 'Dermatologist specialist',
    organization: 'Director of Skin Care Center',
    rating: 4.9,
    reviews: 780,
    specialtyId: 8,
  },
  {
    id: 13,
    name: 'Dr. David Martinez',
    specialty: 'General Physician',
    organization: 'Family Medicine Specialist',
    rating: 4.6,
    reviews: 340,
    specialtyId: 1,
  },
  {
    id: 14,
    name: 'Dr. Amanda White',
    specialty: 'Neurologist specialist',
    organization: 'Brain & Spine Institute',
    rating: 4.8,
    reviews: 460,
    specialtyId: 5,
  },
  {
    id: 15,
    name: 'Dr. Christopher Brown',
    specialty: 'Cardiologist specialist',
    organization: 'Heart Surgery Department',
    rating: 4.7,
    reviews: 590,
    specialtyId: 2,
  },
  {
    id: 16,
    name: 'Dr. Patricia Garcia',
    specialty: 'Gastroenterologist specialist',
    organization: 'Liver & Digestive Center',
    rating: 4.5,
    reviews: 280,
    specialtyId: 4,
  },
  {
    id: 17,
    name: 'Dr. Kevin Anderson',
    specialty: 'Orthopedist specialist',
    organization: 'Sports Medicine Institute',
    rating: 4.9,
    reviews: 650,
    specialtyId: 3,
  },
  {
    id: 18,
    name: 'Dr. Rachel Taylor',
    specialty: 'Psychiatrist specialist',
    organization: 'Behavioral Health Center',
    rating: 4.6,
    reviews: 370,
    specialtyId: 6,
  },
  {
    id: 19,
    name: 'Dr. Mohammed Ali',
    specialty: 'Gynecologist specialist',
    organization: "Maternity & Women's Care",
    rating: 4.8,
    reviews: 490,
    specialtyId: 7,
  },
  {
    id: 20,
    name: 'Dr. Susan Clark',
    specialty: 'Dermatologist specialist',
    organization: 'Advanced Dermatology Clinic',
    rating: 4.7,
    reviews: 610,
    specialtyId: 8,
  },
  {
    id: 21,
    name: 'Dr. Thomas Moore',
    specialty: 'General Physician',
    organization: 'Primary Care Associates',
    rating: 4.8,
    reviews: 520,
    specialtyId: 1,
  },
  {
    id: 22,
    name: 'Dr. Diana Lewis',
    specialty: 'Neurologist specialist',
    organization: 'Neuro Science Center',
    rating: 4.9,
    reviews: 440,
    specialtyId: 5,
  },
  {
    id: 23,
    name: 'Dr. Mark Jackson',
    specialty: 'Cardiologist specialist',
    organization: 'Cardiovascular Excellence',
    rating: 4.6,
    reviews: 380,
    specialtyId: 2,
  },
  {
    id: 24,
    name: 'Dr. Anna Petrov',
    specialty: 'Gastroenterologist specialist',
    organization: 'Digestive Health Institute',
    rating: 4.7,
    reviews: 300,
    specialtyId: 4,
  },
  {
    id: 25,
    name: 'Dr. Ryan Murphy',
    specialty: 'Orthopedist specialist',
    organization: 'Joint Replacement Center',
    rating: 4.8,
    reviews: 470,
    specialtyId: 3,
  },
  {
    id: 26,
    name: 'Dr. Catherine Wright',
    specialty: 'Psychiatrist specialist',
    organization: 'Mind Wellness Institute',
    rating: 4.5,
    reviews: 290,
    specialtyId: 6,
  },
  {
    id: 27,
    name: 'Dr. Hassan Ahmed',
    specialty: 'Gynecologist specialist',
    organization: "Women's Health Specialists",
    rating: 4.9,
    reviews: 560,
    specialtyId: 7,
  },
  {
    id: 28,
    name: 'Dr. Victoria Stone',
    specialty: 'Dermatologist specialist',
    organization: 'Cosmetic & Medical Dermatology',
    rating: 4.8,
    reviews: 720,
    specialtyId: 8,
  },
  {
    id: 29,
    name: 'Dr. Benjamin Foster',
    specialty: 'General Physician',
    organization: 'Community Health Center',
    rating: 4.7,
    reviews: 410,
    specialtyId: 1,
  },
  {
    id: 30,
    name: 'Dr. Olivia Cooper',
    specialty: 'Neurologist specialist',
    organization: 'Advanced Neurology Group',
    rating: 4.8,
    reviews: 350,
    specialtyId: 5,
  },
]




export const PRIVACY_POLICY_URL = 'https://example.com/privacy-policy'
export const TERMS_OF_SERVICE_URL = 'https://example.com/terms-of-service'